abstract final class Commands {
  static const int login = 1;
  static const int register = 2;
  static const int loadInfoAll = 3;
  static const int messageTo = 5;
  static const int roomList = 6;
  static const int roomWaitList = 7;
  static const int joinRoomWait = 8;
  static const int chat = 9;
  static const int kick = 11;
  static const int leaveRoomWait = 15;
  static const int ready = 16;
  static const int confirm = 17;
  static const int bet = 19;
  static const int startGame = 20;
  static const int move = 21;
  static const int shoot = 22;
  static const int setTurn = 24;
  static const int setWind = 25;
  static const int useItem = 26;
  static const int quickPlay = 28;
  static const int friendList = 29;
  static const int addFriend = 32;
  static const int deleteFriend = 33;
  static const int userInfo = 34;
  static const int findUser = 36;
  static const int ping = 42;
  static const int log =
      45; // SessionHandler.log — server notice / auth failure
  static const int skipTurn = 49;
  static const int setXy = 53;
  static const int dynamicSync = 90;
  static const int idNotCollision = 92;
  static const int changeTeam = 71;
  static const int buyItem = 72;
  static const int buyGlass = 74;
  static const int selectMap = 75;
  static const int getKey = -27;
  static const int requestRenewal = -25;
  static const int missions = -23;
  static const int roomInfoNames = -19;
  static const int topInfo = -14;
  static const int quit = -4;
  static const int shopSpecial = -3;
  static const int setEquipVip = -2;
}
